# Generated by Django 2.2.2 on 2020-04-06 01:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apiinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=64)),
                ('indate', models.DateTimeField(default=django.utils.timezone.now)),
                ('outdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('addr', models.CharField(default='', max_length=64, null=True)),
                ('status', models.CharField(default='', max_length=64, null=True)),
                ('tool', models.CharField(default='', max_length=64, null=True)),
                ('model', models.CharField(default='', max_length=64, null=True)),
                ('api', models.CharField(default='', max_length=64, null=True)),
                ('param', models.TextField(default='', null=True)),
                ('desc', models.TextField(default='', null=True)),
            ],
            options={
                'ordering': ('indate', 'user'),
            },
        ),
        migrations.CreateModel(
            name='dashitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('memo', models.TextField(default='', max_length=64)),
                ('enable', models.BooleanField(default=False)),
                ('asdefault', models.BooleanField(default=False)),
                ('owner', models.TextField(default='*', null=True)),
                ('menuindex', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='loginfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=64)),
                ('logdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(default='', max_length=64, null=True)),
                ('status', models.CharField(default='', max_length=64, null=True)),
                ('addr', models.CharField(default='', max_length=64, null=True)),
                ('os', models.CharField(default='', max_length=64, null=True)),
                ('osver', models.CharField(default='', max_length=64, null=True)),
                ('browser', models.CharField(default='', max_length=64, null=True)),
                ('browserver', models.CharField(default='', max_length=64, null=True)),
                ('device', models.CharField(default='', max_length=64, null=True)),
                ('memo', models.TextField(default='', null=True)),
            ],
            options={
                'ordering': ('logdate', 'user'),
            },
        ),
    ]
